---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: labeldeny
webhooks:
  - name: labeldeny.example.com
    rules:
    - apiGroups:
      - "*"
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
    failurePolicy: Fail
    clientConfig:
      url: "https://example.com/administer"
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
